ALTER TYPE "countries" ADD VALUE 'AF';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'AL';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'DZ';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'AS';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'AD';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'AO';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'AI';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'AQ';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'AG';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'AR';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'AM';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'AW';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'AU';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'AT';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'AZ';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'BS';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'BH';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'BD';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'BB';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'BY';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'BE';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'BZ';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'BJ';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'BM';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'BT';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'BO';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'BA';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'BW';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'BV';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'IO';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'BN';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'BG';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'BF';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'BI';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'KH';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'CM';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'CA';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'CV';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'KY';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'CF';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'TD';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'CL';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'CN';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'CX';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'CC';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'CO';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'KM';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'CG';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'CD';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'CK';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'CR';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'CI';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'HR';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'CU';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'CY';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'CZ';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'DK';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'DJ';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'DM';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'DO';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'EC';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'EG';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'SV';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'GQ';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'ER';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'EE';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'ET';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'FK';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'FO';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'FJ';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'FI';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'FR';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'GF';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'PF';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'TF';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'GA';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'GM';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'GE';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'DE';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'GH';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'GI';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'GR';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'GL';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'GD';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'GP';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'GU';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'GT';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'GG';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'GN';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'GW';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'GY';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'HT';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'HM';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'VA';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'HN';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'HK';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'HU';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'IS';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'IN';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'ID';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'IR';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'IQ';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'IE';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'IM';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'IL';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'IT';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'JM';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'JP';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'JE';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'JO';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'KZ';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'KE';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'KI';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'KP';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'KR';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'KW';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'KG';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'LA';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'LV';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'LB';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'LS';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'LR';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'LY';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'LI';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'LT';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'LU';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'MO';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'MK';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'MG';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'MW';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'MY';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'MV';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'ML';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'MT';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'MH';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'MQ';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'MR';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'MU';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'YT';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'MX';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'FM';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'MD';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'MC';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'MN';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'ME';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'MS';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'MA';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'MZ';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'MM';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'NA';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'NR';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'NP';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'NL';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'AN';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'NC';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'NZ';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'NI';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'NE';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'NG';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'NU';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'NF';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'MP';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'NO';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'OM';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'PK';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'PW';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'PS';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'PA';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'PG';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'PY';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'PE';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'PH';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'PN';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'PL';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'PT';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'PR';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'QA';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'RE';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'RO';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'RU';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'RW';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'SH';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'KN';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'LC';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'PM';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'VC';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'WS';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'SM';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'ST';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'SA';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'SN';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'RS';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'SC';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'SL';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'SG';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'SK';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'SI';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'SB';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'SO';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'ZA';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'GS';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'ES';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'LK';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'SD';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'SR';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'SJ';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'SZ';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'SE';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'CH';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'SY';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'TW';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'TJ';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'TZ';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'TH';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'TL';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'TG';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'TK';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'TO';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'TT';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'TN';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'TR';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'TM';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'TC';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'TV';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'UG';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'UA';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'AE';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'GB';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'UM';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'UY';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'UZ';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'VU';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'VE';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'VN';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'VG';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'VI';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'WF';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'EH';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'YE';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'ZM';--> statement-breakpoint
ALTER TYPE "countries" ADD VALUE 'ZW';